/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
<<<<<<< HEAD
    @Test 
	public void testSmallPrime() {
        App appObj = new App();
        assertEquals(appObj.isPrime(17),true);
    }
	@Test 
	public void testSmallNoPrime() {
        App appObj = new App();
        assertEquals(appObj.isPrime(33),false);
    }
	@Test 
	public void testLargePrime() {
        App appObj = new App();
        assertEquals(appObj.isPrime(32416189049L),true);
    }
	@Test 
	public void testLargeNoPrime() {
        App appObj = new App();
        assertEquals(appObj.isPrime(32416189051L),false);
=======
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
>>>>>>> master
    }
}
